# Generated by Django 5.1 on 2024-08-26 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_alter_employee_date_joined_employee_categ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2024, 8, 25, 20, 58, 26, 418514), verbose_name='Fecha de registro'),
        ),
    ]
