# Generated by Django 5.1 on 2024-08-26 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_employee_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='categ',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2024, 8, 25, 21, 0, 47, 82934), verbose_name='Fecha de registro'),
        ),
    ]
