# Generated by Django 5.1 on 2024-08-29 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_categ_employee_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cvitae',
            field=models.FileField(blank=True, null=True, upload_to='cvitae/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2024, 8, 29, 11, 40, 13, 110392), verbose_name='Fecha de registro'),
        ),
    ]
