# Generated by Django 5.1 on 2024-08-29 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employee_cvitae_employee_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2024, 8, 29, 11, 42, 33, 665275), verbose_name='Fecha de registro'),
        ),
    ]
